### ISSUE TITLE
Corrigir alterar/exibir evento

### ISSUE THREAD

**Issue by sergiogambarra** [MacasRenata/Sistema-Eventos#6]
- Ao exibir evento tem que mostrar um check box ao inves de "true" ou "false" nos campos boleanos.
- Ao exibir evento e clicar em "alterar", não abre a pagina de alteração.

**Comment by macasrenata** [comment]
Resolvido a tela de 'consultaEvento' >> Maçãs

a resolução do 'alterarEvento' esta sendo resolvida por @drumluis

**Comment by macasrenata** [comment]
Corrigido por @drumluis
