### ISSUE TITLE
Corrigir alterar/exibir Usuario

### ISSUE THREAD

**Issue by sergiogambarra** [MacasRenata/Sistema-Eventos#8]
Ao exibir não puxa os dados do usuario e o botão alterar também não funciona

**Comment by macasrenata** [comment]
Resolvido a tela de 'consultarUsuario' >> Maçãs

AlterarEvento + AlterarUsuario esta sendo resolvido por @drumluis

**Comment by macasrenata** [comment]
Corrigido por @drumluis
