### ISSUE TITLE
Mensagens erradas na validação de datas

### ISSUE THREAD

**Issue by sergiogambarra** [MacasRenata/Sistema-Eventos#9]
Ao tentar cadastrar evento com datas erradas o sistema não realiza o cadastro, avisa que datas estão incorretas entretanto avista também que o cadastro foi realizado corretamente.

**Comment by macasrenata** [comment]
Resolvido o cadastramento de evento  >> Maçãs

-- As datas ainda não foram configuradas por @sergiogambarra

**Comment by sergiogambarra** [comment]
Feito
